---
- hosts: localhost
  vars:
    downloads_dir: "{{ playbook_dir }}/downloads"
  vars_prompt:
    - name: kubernetes_version
      prompt: kubernetes version
      default: "v1.3.4"
      private: no
  tasks:
    - name: Build kube-registry-proxy image
      docker_image:
        path: "{{ downloads_dir }}/kubernetes-{{ kubernetes_version }}/kubernetes/cluster/addons/registry/images"
        push: no
        name: 127.0.0.1:5000/google_containers/kube-registry-proxy
        tag: 0.3
        archive_path: "/tmp/kube-registry-proxy.tar"

    - name: Build cassandra debian image
      docker_image:
        path: images/cassandra/3.7/debian
        push: no
        name: 127.0.0.1:5000/infra/cassandra37x
        tag: 0.1
        archive_path: "/tmp/cassandra37.tar"

    - name: Build cassandra alpine image
      docker_image:
        path: images/cassandra/3.7/alpine
        push: no
        name: 127.0.0.1:5000/infra/cassandra:3.7-alpine
        tag: 0.1
        archive_path: "/tmp/cassandra37-alpine.tar"
        force: yes

- hosts: nodes
  become: yes
  tasks:
    - apt: name=python-docker
    
    - copy: src=/tmp/kube-registry-proxy.tar dest=/tmp/kube-registry-proxy.tar
    - name: Load image from kube-registry-proxy.tar archive
      docker_image:
        name: 127.0.0.1:5000/google_containers/kube-registry-proxy
        tag: 0.3
        load_path: /tmp/kube-registry-proxy.tar
        push: no

    - copy: src=/tmp/cassandra37.tar dest=/tmp/cassandra37.tar
    - name: Load image from cassandra37.tar archive
      docker_image:
        name: 127.0.0.1:5000/infra/cassandra37x
        tag: 0.1
        load_path: /tmp/cassandra37.tar
        push: no

    - copy: src=/tmp/cassandra37-alpine.tar dest=/tmp/cassandra37-alpine.tar
    - name: Load image from /tmp/cassandra37-alpine.tar archive
      docker_image:
        name: 127.0.0.1:5000/infra/cassandra
        tag: 3.7-alpine
        load_path: /tmp/cassandra37-alpine.tar
        push: no
