- name: build etcd cluster
  hosts: etcd
  roles:
    - { role: etcd, etcd_version: '2.2.5+dfsg-1', tags: [ 'etcd' ] }

- name: setup k8s
  hosts: k8s
  become: yes
  vars:
    downloads_dir: "{{ playbook_dir }}/downloads"
  roles:
    - { role: docker, docker_version: '1.11.2-0~xenial', tags: [ 'docker', 'node' ] }
    - { role: flannel, flannel_version: '0.5.5', tags: [ 'flannel', 'node' ] }
    - { role: glusterfs, glusterfs_version: '3.7.6-1ubuntu1', tags: [ 'glusterfs', 'node' ] }
    - { role: master, kubernetes_version: 'v1.3.3', tags: [ 'master' ] }
