---
- name: create ssh connection
  hosts: localhost
  connection: local
  vars_prompt:
    - name: cows_path
      prompt: cows file path
      default: xenial
      private: no
    - name: identify_file
      prompt: ssh public key location
      default: "~/.ssh/id_rsa.pub"
      private: no
    - name: cows_pass
      prompt: cows default passwd
  tasks:
    - command: |
        sshpass -p {{ cows_pass }}
        ssh-copy-id
          -i {{ identify_file }}
          -o StrictHostKeyChecking=no {{ item }}
      with_lines: 
        - "cat {{ cows_path }}"
      name: ssh-copy-id

- name: install python 2.7
  hosts: xenial
  gather_facts: false
  tasks:
    - name: install python 2.7
      raw: sudo apt update && sudo apt install -y python2.7
      tags:
        - upgrade
    - raw: python -V
    - raw: sudo apt upgrade -y
      tags:
        - upgrade

- name: install ansible needs
  hosts: xenial
  gather_facts: true
  pre_tasks:
  tasks:
    - name: "install {{ item }}"
      apt: >
        name={{ item }}
        update_cache=yes
        cache_valid_time=86400
        state=present 
      with_items:
        - python-httplib2
        - bridge-utils
        - pptp-linux
        - iftop
        - htop
        - fish
      become: yes
      tags:
        - upgrade
  post_tasks:
