- name: setup single master
  vars_prompt:
      - name: kube_apiserver_host
        prompt: kubernetes api server
        default: master2
        private: no
      - name: kubernetes_version
        prompt: kubernetes version
        default: "v1.3.4"
        private: no
  hosts: "{{ kube_apiserver_host }}"
  become: yes
  vars_files:
    - vars_files/kube.yml
  vars:
    downloads_dir: "{{ playbook_dir }}/downloads"
  roles:
    - { role: etcd, etcd_version: '2.2.5+dfsg-1', tags: [ 'etcd' ] }
    - { role: glusterfs, glusterfs_version: '3.7.6-1ubuntu1', tags: [ 'pv' ] }
    - { role: master, tags: [ 'master' ] }
