---
- name: variables exmaples
  hosts: nodes
  tasks:
    - setup: filter=ansible_all_ipv4_addresses
      name: gather facts
      register: r
      delegate_to: "{{ groups['etcd'][0] }}"
      run_once: yes
    - debug: var=r
    #- debug: var=hostvars
    #- debug: var=inventory_hostname
    #- debug: var=hostvars[inventory_hostname]
    #    - debug: var=hostvars[inventory_hostname]['ansible_default_ipv4']
    #    - debug: var=groups
    #    - debug: var=groups['etcd']
    # - debug: var=inventory_hostname
    # - debug: var=hostvars
    - debug: var=groups['etcd'][0]
    # - shell: uname -a
    #   delegate_to: imac
    #   register: r
    # - debug: var=r
    # - debug: var=ansible_default_ipv4

