---
- name: update grub
  command: update-grub

- name: reboot machine
  shell: sleep 2 && shutdown -r now
  async: 600
  poll: 0
  ignore_errors: true

- name: "wait server back"
  local_action: >
      wait_for host={{ ansible_host }}
      port={{ ansible_port }}
      state=started
      delay=5
      timeout=600
      connect_timeout=30
  become: no


# references: http://docs.ansible.com/ansible/playbooks_async.html