---
- name: reload systemd
  command: systemctl daemon-reload

- name: restart flannel
  service: >
    name=flannel
    state=restarted

- name: restart docker
  service: >
    name=docker
    state=restarted