---

etcd_endpoints: "http://{{ master_ip }}:2379"

# A CIDR notation IP range from which to assign service cluster IPs.
# This must not overlap with any IP ranges assigned to nodes for pods.
service_cluster_ip_range: "10.254.0.0/16"

dns_domain: cluster.local

service_ip: "10.254.0.1"

req_cn: "{{ master_ip }}@{{lookup('pipe', 'date +%s')}}"

sans: "IP:{{ master_ip }},IP:{{ service_ip }},DNS:kubernetes,DNS:kubernetes.default,DNS:kubernetes.default.svc,DNS:kubernetes.default.svc.{{ dns_domain }},DNS:{{ master_hostname }}"