---

- include: "skydns.yml"

- include: "registry.yml"

# - shell: |
#     echo \"{{ lookup('template', 'skydns-svc.yaml.j2') }}\" | /usr/local/bin/kubectl apply -f -
#   register: skydns
#   failed_when: skydns.rc != 0


# - shell: "echo \"\'{{ lookup('template', 'skydns-rc.yaml.j2') }}\'\" | /usr/local/bin/kubectl apply -f -"
#   register: skydns
#   failed_when: skydns.rc != 0

# - debug: var=skydns
   

