apiVersion: v1
kind: Pod
metadata:
  name: cassandra-tools
  namespace: default
spec:
  containers:
  - image: 127.0.0.1:5000/inu/cassandra-tools:3.7-alpine
    command:
      - "sh"
      - "-c"
      - "echo 'running since '`date +'%r'`; while true; do sleep 600; done"
    imagePullPolicy: IfNotPresent
    name: cassandra 
  restartPolicy: Always
