
- name: install glusterfs-server
  apt: name=glusterfs-server={{ glusterfs_version }}

- service: name=glusterfs-server state=started enabled=yes
  
- name: install glusterfs-client
  apt: name=glusterfs-client={{ glusterfs_version }}

- name: add kubernetes glusterfs-cluster endpoint
  debug: msg="{{ lookup('template', 'glusterfs-cluster-ep.yml.j2') }}"

# - tmplate: >
#     src=glusterfs-cluster-ep.yml.j2
#     dest=/tmp/glusterfs-cluster-ep.yml
  
