---
- file: >
    path=/etc/systemd/system/docker.service.d 
    state=directory 
    mode=0644
  name: docker drop-ins directory must be present

- copy: >
    src=flannel.conf
    dest=/etc/systemd/system/docker.service.d/flannel.conf
    mode=0644

- lineinfile:
    dest: "/lib/systemd/system/docker.service"
    backrefs: yes
    regexp: "^ExecStart=/usr/bin/docker daemon -H fd://"
    line: "ExecStart=/usr/bin/docker daemon -H fd:// $DOCKER_OPTS"
  name: add $DOCKER_OPTS to docker.service ExecStart