---
- copy: >
    src="{{ downloads_dir }}/kubernetes-{{ kubernetes_version }}/bin/hyperkube"
    dest="/usr/local/bin/hyperkube"
    mode=0750
  tags:
    - "upgrade:{{ kubernetes_version }}"
  name: copy hyperkube

- include: "kubelet.yml"

- include: "kube-proxy.yml"

- include: "gen_tls_keypairs.yml"

# - file: path="{{ item }}" state=directory mode=0751 owner="{{ ansible_user }}"
#   with_items:
#     - "{{ lookup('env','HOME') }}/.kube"
#   name: set user home directory permision

# - file: >
#     src=/var/lib/kubelet/kubeconfig
#     dest="{{ lookup('env','HOME') }}/.kube/config"
#     state=link
#     owner="{{ ansible_user }}"
