apiVersion: v1
kind: Pod
metadata:
  name: busybox
  namespace: default
spec:
  containers:
  - image: busybox
    command:
      - "sh"
      - "-c"
      - "echo 'running since '`date +'%r'`; while true; do sleep 600; done"
    imagePullPolicy: IfNotPresent
    name: busybox
  restartPolicy: Always