---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: es-client
spec:
  replicas: 2
  template:
    metadata:
      labels:
        elasticsearch: client
    spec:
      containers:
      - name: client
        image: "127.0.0.1:5000/inu/elasticsearch:latest"
        imagePullPolicy: IfNotPresent
        #command: [ "/usr/local/bin/dumb-init", "--" ]
        args: [ "/usr/local/bin/run.sh", "/opt/elasticsearch/bin/elasticsearch" ]
        #command: [ "sh", "-c", "echo 'running since '`date +'%r'`; while true; do sleep 600; done"]
        ports:
        - containerPort: 9300
          name: transport
        - containerPort: 9200
          name: http
        resources:
          limits:
            cpu: "1"
            memory: "8Gi"
          requests:
           cpu: "1"
           memory: "8Gi"
        securityContext:
          privileged: true
        env:
          - name: CLUSTER_NAME
            value: inu
          - name: ES_HEAP_SIZE
            value: "4096m"
          - name: NODE_MASTER
            value: "false"
          - name: NODE_DATA
            value: "false"
          - name: HTTP_ENABLE
            value: "true"
          - name: ZEN_HOSTS
            value: es-master-0.elasticsearch-discovery.default.svc.cluster.local