---
- copy: >
    src="{{ downloads_dir }}/kubernetes-{{ kubernetes_version }}/bin/kubernetes/server/bin/hyperkube"
    dest="/usr/local/bin/hyperkube"
    mode=0744

- copy: >
    src="{{ item }}.service"
    dest="/lib/systemd/system/{{item}}.service"
  with_items:
    - kube-apiserver
    - kube-controller-manager
    - kube-scheduler

- template: >
    src="{{ item }}.j2"
    dest="/etc/default/{{ item }}"
  with_items:
    - kube-apiserver
    - kube-controller-manager
    - kube-scheduler

# - service: >
#     name="{{ item }}"
#     state=started
#     enabled=yes
#   with_items:
#     - kube-apiserver
#     - kube-controller-manager
#     - kube-scheduler

