---
- include: "cgroup.yml"
  name: config cgroup

# - apt_key: >
#     keyserver=hkp://p80.pool.sks-keyservers.net:80 
#     id=58118E89F3A912897C070ADBF76221572C52609D
- apt_key: keyserver=keyserver.ubuntu.com id=58118E89F3A912897C070ADBF76221572C52609D

- apt_repository: >
    repo='deb https://apt.dockerproject.org/repo ubuntu-xenial main'
    state=present
    update_cache=yes

- apt: >
    name=docker-engine={{ docker_version }} 
    state=present
    update_cache=yes

# - shell: |
#     curl -fsSL https://get.docker.com/ | sh
#   become: yes
#   name: install docker
