---
apiVersion: v1
kind: Service
metadata:
  name: jenkins
spec:
  type: NodePort
  selector:
    app: jenkins-master
  ports:
    - name: http
      port: 8080
    - name: jnlp
      port: 50000
---
apiVersion: v1
kind: Pod
metadata:
  name: jenkins-master
  labels:
    app: jenkins-master
spec:
  containers:
    - name: jenkins
      image: 127.0.0.1:5000/inu/jenkins:2.19.3-alpine
      imagePullPolicy: IfNotPresent
      resources:
        limits:
          cpu: 500m
          memory: 2500Mi
        requests:
          memory: 1024Mi
      #command: ["/bin/tini", "--", "/usr/local/bin/jenkins.sh"]
      ports:
        - containerPort: 8080
        - containerPort: 50000
      volumeMounts:
        - name: data
          mountPath: /var/jenkins_home
      env:
        - name: JAVA_OPTS
          value: "-Dorg.apache.commons.jelly.tags.fmt.timeZone=Asia/Taipei"
        - name: TRY_UPGRADE_IF_NO_MARKER
          value: "true"
#      securityContext:
#        privileged: true
  volumes:
    - name: data
      glusterfs:
        endpoints: gluster
        path: jenkins
        readOnly: false
